credentials:
  usernames:
    admin:
      email: intel@moodlightintel.com
      name: Admin
      password: $2b$12$OXpPytylZIVxruJW3ZlJaObkM3r1LKB6ec9So45oYKm2hqBOMhh36
      failed_login_attempts: 0
      logged_in: False

    ariellesantiago:
      email: arielle.santiago@civic-us.com
      name: Arielle
      password: $2b$12$kWgvAOiRlwVlSJRFd5PA.OdI7rml7Qui/3AM554uts/njvcr6y1nm
      failed_login_attempts: 0
      logged_in: False

cookie:
  expiry_days: 30
  key: moodlight_auth_key_2025
  name: moodlight_auth
